name: Linode Cleanup

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "0 */8 * * *"

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Linode CLI
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip3 install linode-cli

      - name: Cleanup
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
        run: |
          ./hack/scripts/linode-cleanup.sh
          ./hack/scripts/linode-cleanup.sh
          ./hack/scripts/linode-cleanup.sh
