name: Linode Cleanup

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Linode CLI
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install linode-cli --upgrade

      - name: Cleanup
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
        run: |
          ./hack/scripts/linode-cleanup.sh
